### PR TITLE
RN: Prevent conversion of ReadableMap to HashMap

### LINKED ISSUE #479: RN: Unexpected type java.util.HashMap
There is a Runtime Error being caused when converting a ReadableArray to an ArrayList where any nested objects are converted to HashMap instead of kept as ReadableMap. This causes an error when converting ReadableMap data to the correct types.

```
 LOG  error: Error: Unexpected type java.util.HashMap
 LOG  Error: {
  "nativeStackAndroid": [
    {
      "lineNumber": 1928,
      "file": "BreezSDKLiquidMapper.kt",
      "methodName": "asRouteHintList",
      "class": "com.breezsdkliquid.BreezSDKLiquidMapperKt"
    },
    {
      "lineNumber": 449,
      "file": "BreezSDKLiquidMapper.kt",
      "methodName": "asLnInvoice",
      "class": "com.breezsdkliquid.BreezSDKLiquidMapperKt"
    },
    {
      "lineNumber": 2696,
      "file": "BreezSDKLiquidMapper.kt",
      "methodName": "asSendDestination",
      "class": "com.breezsdkliquid.BreezSDKLiquidMapperKt"
    },
    {
      "lineNumber": 1604,
      "file": "BreezSDKLiquidMapper.kt",
      "methodName": "asPrepareSendResponse",
      "class": "com.breezsdkliquid.BreezSDKLiquidMapperKt"
    },
    {
      "lineNumber": 1998,
      "file": "BreezSDKLiquidMapper.kt",
      "methodName": "asSendPaymentRequest",
      "class": "com.breezsdkliquid.BreezSDKLiquidMapperKt"
    },
    {
      "lineNumber": 248,
      "file": "BreezSDKLiquidModule.kt",
      "methodName": "sendPayment$lambda$16",
      "class": "com.breezsdkliquid.BreezSDKLiquidModule"
    },
    {
      "lineNumber": 0,
      "file": null,
      "methodName": "$r8$lambda$Zxit_m4FM3h8Ct7BxrLazasgsMM",
      "class": "com.breezsdkliquid.BreezSDKLiquidModule"
    },
    {
      "lineNumber": 6,
      "file": null,
      "methodName": "run",
      "class": "com.breezsdkliquid.BreezSDKLiquidModule$$ExternalSyntheticLambda21"
    },
    {
      "lineNumber": 1137,
      "file": "ThreadPoolExecutor.java",
      "methodName": "runWorker",
      "class": "java.util.concurrent.ThreadPoolExecutor"
    },
    {
      "lineNumber": 637,
      "file": "ThreadPoolExecutor.java",
      "methodName": "run",
      "class": "java.util.concurrent.ThreadPoolExecutor$Worker"
    },
    {
      "lineNumber": 1012,
      "file": "Thread.java",
      "methodName": "run",
      "class": "java.lang.Thread"
    }
  ],
  "userInfo": null,
  "message": "Unexpected type java.util.HashMap",
  "code": "Generic",
  "line": 2004,
  "column": 45,
  "sourceURL": "http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.example.breezsdkliquid&modulesOnly=false&runModule=true"
}

### PR DESCRIPTION
**Pull request by dangeross**
This PR adds a function to replace ReadableArray.toArrayList() to prevent any nested objects being converted to HashMap instead of kept as ReadableMap.

Fixes #479

### CODE REVIEW

**Review by erdemyerebasmaz — APPROVED** [review]
LGTM

File: lib/bindings/langs/react-native/src/gen_kotlin/templates/Helpers.kt [hunk 1]
```diff
@@ -63,6 +63,21 @@ fun readableArrayOf(values: Iterable<*>?): ReadableArray {
     return array
 }
 
+fun asArrayList(arr: ReadableArray): ArrayList<Any> {
+    val arrayList = ArrayList<Any>();
+    for (i in 0..arr.size()-1) {
+        when (arr.getType(i)) {
```
Comment (roeierez) [inline lib/bindings/langs/react-native/src/gen_kotlin/templates/Helpers.kt:69]: Seems like ReadableArray also has type Null. Should we assign null in this case? https://github.com/jackuhan/AndroidMonitor/blob/master/app/src/main/java/com/facebook/react/bridge/ReadableType.java#L18

**Review by roeierez — CHANGES_REQUESTED** [review]

File: lib/bindings/langs/react-native/src/gen_kotlin/templates/Helpers.kt (hunk 1 above)
Comment (dangeross) [reply lib/bindings/langs/react-native/src/gen_kotlin/templates/Helpers.kt]: Even though we don't have a case were we have optional elements in an array, we should support at least the conversion to a List with nullable elements. Done [92ff98f](https://github.com/breez/breez-sdk-liquid/pull/482/commits/92ff98ff7889ff4de501cfbf2b146021d40e0027)

**Review by roeierez — APPROVED** [review]
