### PR TITLE
Retry chain swap server lockup tx verification

### LINKED ISSUE #547: Failure to verify confirmed server transaction prevents claim
During an incoming chain swap and we receive a `transaction.server.confirmed` status, if we fail to verify that the transaction is confirmed then the swap stalls (until the SDK is next started)

```
[2024-11-06 14:58:55.369 INFO breez_sdk_liquid::swapper::boltz::status_stream:119] Received text msg: "{\"event\":\"update\",\"channel\":\"swap.update\",\"args\":[{\"id\":\"GHMXTonc4H2Y\",\"status\":\"transaction.server.mempool\",\"transaction\":{\"id\":\"4f99a6d156af49054c40cc5c62d98cacc6c21df95c7e339d0680e60fcc31fbd1\",\"hex\":\"...\",\"eta\":2}}],\"timestamp\":\"1730901535425\"}"
[2024-11-06 14:58:55.376 INFO breez_sdk_liquid::chain_swap:258] Handling incoming Chain Swap transition to "transaction.server.mempool" for swap GHMXTonc4H2Y
[2024-11-06 14:58:55.379 INFO boltz_client::swaps::liquid:367] Taproot creation and verification success!
[2024-11-06 14:58:55.380 INFO breez_sdk_liquid::chain::liquid:184] Fetching script history for d57271c00986481f9edfdbe3e9aaa06abe4d7196cda964c6d2847f122be6d302
[2024-11-06 14:58:55.380 INFO breez_sdk_liquid::chain::liquid:279] liquid chain service get_with_retry for url https://lq1.breez.technology/liquid/api/scripthash/d57271c00986481f9edfdbe3e9aaa06abe4d7196cda964c6d2847f122be6d302/txs
[2024-11-06 14:58:55.381 DEBUG reqwest::connect:429] starting new connection: https://lq1.breez.technology/
[2024-11-06 14:58:55.729 INFO breez_sdk_liquid::chain::liquid:193] Script history for d57271c00986481f9edfdbe3e9aaa06abe4d7196cda964c6d2847f122be6d302 is empty, retrying in 1 second... (1 of 30)
[2024-11-06 14:58:56.731 INFO breez_sdk_liquid::chain::liquid:279] liquid chain service get_with_retry for url https://lq1.breez.technology/liquid/api/scripthash/d57271c00986481f9edfdbe3e9aaa06abe4d7196cda964c6d2847f122be6d302/txs
[2024-11-06 14:58:56.731 DEBUG reqwest::connect:429] starting new connection: https://lq1.breez.technology/
[2024-11-06 14:58:57.020 INFO breez_sdk_liquid::chain::liquid:193] Script history for d57271c00986481f9edfdbe3e9aaa06abe4d7196cda964c6d2847f122be6d302 is empty, retrying in 1 second... (2 of 30)
[2024-11-06 14:58:58.022 INFO breez_sdk_liquid::chain::liquid:279] liquid chain service get_with_retry for url https://lq1.breez.technology/liquid/api/scripthash/d57271c00986481f9edfdbe3e9aaa06abe4d7196cda964c6d2847f122be6d302/txs
[2024-11-06 14:58:58.022 DEBUG reqwest::connect:429] starting new connection: https://lq1.breez.technology/
[2024-11-06 14:58:58.308 INFO breez_sdk_liquid::chain::liquid:193] Script history for d57271c00986481f9edfdbe3e9aaa06abe4d7196cda964c6d2847f122be6d302 is empty, retrying in 1 second... (3 of 30)
[2024-11-06 14:58:58.511 DEBUG breez_sdk_liquid::swapper::boltz::status_stream:143] Received ping
[2024-11-06 14:58:58.519 DEBUG breez_sdk_liquid::swapper::boltz::status_stream:101] Sent keep-alive ping
[2024-11-06 14:58:58.699 DEBUG breez_sdk_liquid::swapper::boltz::status_stream:144] Received pong
[2024-11-06 14:58:59.312 INFO breez_sdk_liquid::chain::liquid:279] liquid chain service get_with_retry for url https://lq1.breez.technology/liquid/api/scripthash/d57271c00986481f9edfdbe3e9aaa06abe4d7196cda964c6d2847f122be6d302/txs
[2024-11-06 14:58:59.312 DEBUG reqwest::connect:429] starting new connection: https://lq1.breez.technology/
[2024-11-06 14:58:59.615 INFO breez_sdk_liquid::chain::liquid:250] Liquid transaction found, verifying transaction content...
[2024-11-06 14:58:59.632 INFO breez_sdk_liquid::chain_swap:298] Server lockup mempool transaction was verified for incoming Chain Swap GHMXTonc4H2Y
[2024-11-06 14:58:59.632 INFO breez_sdk_liquid::chain_swap:664] Transitioning Chain swap GHMXTonc4H2Y to Pending (server_lockup_tx_id = Some("4f99a6d156af49054c40cc5c62d98cacc6c21df95c7e339d0680e60fcc31fbd1"), user_lockup_tx_id = None, claim_tx_id = None), refund_tx_id = None)
[2024-11-06 14:58:59.634 INFO breez_sdk_liquid::sdk:344] Successfully handled Chain Swap GHMXTonc4H2Y update
[2024-11-06 14:59:03.350 INFO breez_sdk_liquid::sdk:2165] Synchronized with mempool and onchain data (t = 1269 ms)
[2024-11-06 14:59:03.350 INFO breez_liquid_cli:46] Received event: Synced
[2024-11-06 14:59:13.511 DEBUG breez_sdk_liquid::swapper::boltz::status_stream:143] Received ping
[2024-11-06 14:59:13.518 DEBUG breez_sdk_liquid::swapper::boltz::status_stream:101] Sent keep-alive ping
[2024-11-06 14:59:13.693 DEBUG breez_sdk_liquid::swapper::boltz::status_stream:144] Received pong
[2024-11-06 14:59:28.510 DEBUG breez_sdk_liquid::swapper::boltz::status_stream:143] Received ping
[2024-11-06 14:59:28.518 DEBUG breez_sdk_liquid::swapper::boltz::status_stream:101] Sent keep-alive ping
[2024-11-06 14:59:28.690 DEBUG breez_sdk_liquid::swapper::boltz::status_stream:144] Received pong
[2024-11-06 14:59:34.768 INFO breez_sdk_liquid::sdk:2165] Synchronized with mempool and onchain data (t = 1415 ms)
[2024-11-06 14:59:34.768 INFO breez_liquid_cli:46] Received event: Synced
[2024-11-06 14:59:35.416 INFO breez_sdk_liquid::swapper::boltz::status_stream:119] Received text msg: "{\"event\":\"update\",\"channel\":\"swap.update\",\"args\":[{\"id\":\"GHMXTonc4H2Y\",\"status\":\"transaction.server.confirmed\",\"transaction\":{\"id\":\"4f99a6d156af49054c40cc5c62d98cacc6c21df95c7e339d0680e60fcc31fbd1\",\"hex\":\"...\"}}],\"timestamp\":\"1730901575478\"}"
[2024-11-06 14:59:35.424 INFO breez_sdk_liquid::chain_swap:258] Handling incoming Chain Swap transition to "transaction.server.confirmed" for swap GHMXTonc4H2Y
[2024-11-06 14:59:35.425 INFO boltz_client::swaps::bitcoin:361] Taproot creation and verification success!
[2024-11-06 14:59:35.427 INFO breez_sdk_liquid::chain::bitcoin:163] Fetching script history for 1d063ee83172f7afd8eba05a7326cdc9d78f4a6271bb2bcfcf174e243cdf8e6c
[2024-11-06 14:59:35.427 WARN electrum_client::client:260] call 'script_get_history' failed with unexpected end of file, retry: 1/1
[2024-11-06 14:59:37.498 INFO electrum_client::client:260] Succesfully created new client
[2024-11-06 14:59:37.687 INFO boltz_client::swaps::liquid:367] Taproot creation and verification success!
[2024-11-06 14:59:37.687 INFO breez_sdk_liquid::chain::liquid:184] Fetching script history for d57271c00986481f9edfdbe3e9aaa06abe4d7196cda964c6d2847f122be6d302
[2024-11-06 14:59:37.687 INFO breez_sdk_liquid::chain::liquid:279] liquid chain service get_with_retry for url https://lq1.breez.technology/liquid/api/scripthash/d57271c00986481f9edfdbe3e9aaa06abe4d7196cda964c6d2847f122be6d302/txs
[2024-11-06 14:59:37.688 DEBUG reqwest::connect:429] starting new connection: https://lq1.breez.technology/
[2024-11-06 14:59:37.984 INFO breez_sdk_liquid::chain::liquid:250] Liquid transaction found, verifying transaction content...
[2024-11-06 14:59:37.987 WARN breez_sdk_liquid::chain_swap:332] Server lockup transaction for incoming Chain Swap GHMXTonc4H2Y could not be verified. txid: 4f99a6d156af49054c40cc5c62d98cacc6c21df95c7e339d0680e60fcc31fbd1, err: Liquid transaction was not confirmed, txid=4f99a6d156af49054c40cc5c62d98cacc6c21df95c7e339d0680e60fcc31fbd1 waiting for confirmation
[2024-11-06 14:59:37.987 ERROR breez_sdk_liquid::sdk:345] Failed to handle Chain Swap GHMXTonc4H2Y update: Could not verify server lockup transaction 4f99a6d156af49054c40cc5c62d98cacc6c21df95c7e339d0680e60fcc31fbd1: Liquid transaction was not confirmed, txid=4f99a6d156af49054c40cc5c62d98cacc6c21df95c7e339d0680e60fcc31fbd1 waiting for confirmation
```

### PR DESCRIPTION
**Pull request by dangeross**
This PR retries adds monitoring of the incoming server lockup txs. If a server lockup tx is confirmed without a claim (tx failed verification when receiving the Boltz status), then perform the claim.

Fixes #547

### CODE REVIEW

File: lib/core/src/chain_swap.rs [hunk 1]
```diff
@@ -1122,35 +1124,56 @@ impl ChainSwapHandler {
...
-                    chain_swap,
-                    swap_update_tx,
-                    verify_confirmation,
-                )
-                .await
+        let swap_script = chain_swap.get_claim_swap_script()?;
+        let claim_details = chain_swap.get_boltz_create_response()?.claim_details;
+        let retries = if verify_confirmation { 30 } else { 0 };
+        let mut retry = 0;
+        loop {
```
Comment (roeierez) [inline lib/core/src/chain_swap.rs:1131]: The concern here is that it will block the event status polling loop and may block other payment statuses.

Comment (dangeross) [reply lib/core/src/chain_swap.rs:1131]: I think it would take a only a couple of attempts to get the confirmation, it testing it was confirmed in the first request. Maybe it's better to add it to the tracking thread to verify and claim if needed

**Comment by dangeross** [comment]
I was able to catch a failed confirmation and see it picked up in the monitoring thread
```
[2024-11-10 21:03:35.587 INFO breez_sdk_liquid::chain_swap:323] Handling incoming Chain Swap transition to "transaction.server.confirmed" for swap 4HxGzWthwwaU
[2024-11-10 21:03:38.081 INFO breez_sdk_liquid::chain::liquid:250] Liquid transaction found, verifying transaction content...
[2024-11-10 21:03:38.083 INFO breez_sdk_liquid::chain_swap:732] Transitioning Chain swap 4HxGzWthwwaU to Pending (server_lockup_tx_id = Some("8af223ba1e7ccd05cac077a700cf90fd6f93955e1ea9161bbf9f49c288c33d05"), user_lockup_tx_id = None, claim_tx_id = None), refund_tx_id = None)
[2024-11-10 21:03:38.085 WARN breez_sdk_liquid::chain_swap:413] Server lockup transaction for incoming Chain Swap 4HxGzWthwwaU could not be verified. txid: 8af223ba1e7ccd05cac077a700cf90fd6f93955e1ea9161bbf9f49c288c33d05, err: Liquid transaction was not confirmed, txid=8af223ba1e7ccd05cac077a700cf90fd6f93955e1ea9161bbf9f49c288c33d05 waiting for confirmation

...

[2024-11-10 21:04:33.569 INFO breez_sdk_liquid::chain_swap:227] Rescanning 1 incoming Chain Swap(s) server lockup txs at height 3114131
[2024-11-10 21:04:33.846 INFO breez_sdk_liquid::chain_swap:261] Incoming Chain Swap 4HxGzWthwwaU server lockup tx is confirmed
[2024-11-10 21:04:33.847 DEBUG breez_sdk_liquid::chain_swap:770] Initiating claim for Chain Swap 4HxGzWthwwaU
[2024-11-10 21:04:42.730 INFO breez_sdk_liquid::chain_swap:732] Transitioning Chain swap 4HxGzWthwwaU to Pending (server_lockup_tx_id = None, user_lockup_tx_id = None, claim_tx_id = Some("bbe1b7dda86030489461784ffd70b31ff94531c65190a0607617533523050d55")), refund_tx_id = None)
[2024-11-10 21:04:42.735 INFO breez_liquid_cli:46] Received event: PaymentWaitingConfirmation { details: Payment { destination: Some("lq1qqg6vf68kjwdgalvv3gt58h5fvaz73lmxngq6xnjr62gwhwj6gwrvxmwszry4afz5gka38pys3srkkq22dt9w5tzc8stjm5xy9"), tx_id: Some("bbe1b7dda86030489461784ffd70b31ff94531c65190a0607617533523050d55"), timestamp: 1731269082, amount_sat: 49155, fees_sat: 845, payment_type: Receive, status: Pending, details: Bitcoin { swap_id: "4HxGzWthwwaU", description: "Bitcoin transfer", refund_tx_id: None, refund_tx_amount_sat: None } } }
```

**Review by roeierez — APPROVED** [review]
LGTM

**Review by ok300 — APPROVED** [review]
